.gitlab-ci.yml
Implements integration tests, see [documentation](https://github.com/QEDjl-project/QED.jl/blob/dev/docs/src/ci.md#integration-tests-for-ci-users).
Same Job like in https://github.com/QEDjl-project/QEDbase.jl/pull/2
=> add integration tests

Manifest.toml, Project.toml, src/QEDprocesses.jl, src/interfaces/particle_interface.jl, src/particle_types.jl, test/Manifest.toml, test/Project.toml, test/interfaces/particle_interface.jl, test/particle_types.jl, test/runtests.jl
This MR adds a Julia interface including types and functions to describe particles in the sense of the standard model of particle physics. The description is not restricted to static properties, but can in general be fulfilled by any instance of particles in general. 
Furthermore, this MR contains an implementation of a type hierarchy for Bosons, Fermions, and their respective anti-particles, as well as particle types for Electrons, Positrons, and Photons. Again, the type hierarchy is not restricted to these particle types.
In the implementation, the notion of particles is derived from an abstract type `AbstractParticle` and the following interface functions:
* `is_fermion(::AbstractParticle)`, which returns `true` if the input can be considered as a fermion, and `false` if not.
* …
=> Dev particle interface

Manifest.toml, Project.toml, README.md, docs/Manifest.toml, src/QEDprocesses.jl, src/interfaces/model_interface.jl, src/interfaces/particle_interface.jl, src/interfaces/process_interface.jl, src/particle_types.jl, src/utils.jl, test/Manifest.toml, test/Project.toml, test/interfaces/model_interface.jl, test/interfaces/particle_interface.jl, test/interfaces/process_interface.jl, test/runtests.jl
This PR provides an implementation of the model and process interface, which is also combined with an interface for differential and total cross-sections. 
In this PR, the model interface describes only static information, i.e. there is only one un-parameterized base type and a convenient interface function:
```julia
AbstractModelDefinition
fundamental_interaction_type(::AbstractModelDefiniton)
```
In this PR, the process interface describes only static information about a scattering process. Here, a scattering process should be seen in a generic way, which forms a physical scattering process, if it is combined with a model definition above. 
The process definition interface is defined as 
```julia 
AbstractProcessDefinition     #base type for processes …
```
=> Model and Process interface

src/QEDprocesses.jl, src/interfaces/model_interface.jl, src/interfaces/particle_interface.jl, src/interfaces/process_interface.jl, src/interfaces/setup_interface.jl, src/particle_types.jl, src/utils.jl, test/interfaces/process_interface.jl, test/interfaces/setup_interface.jl, test/runtests.jl
With this PR, the concept of *computation setups* is introduced, and general as well as functionality related to scattering processes is implemented. 
One of the main tasks of this package is the computation of quantities like differential and total cross-section for given scattering processes and a given set of parameters. Usually, these quantities depend on a fixed set of initial parameters, and their value needs to be calculated for large amounts of input data. For example, the differential cross-section of a process depends on the generic scattering process, the compute model, and all sorts of initial parameters, which might be physical (e.g. energy scales) or technical (e.g. integrator settings). Once initialized, the differential cross-section is still a function of the external …
=> Computation and process setup interface

.github/workflows/BuildDelopyDoc.yml, README.md, docs/make.jl
solves #10 
Copy of: https://github.com/QEDjl-project/QEDevents.jl/pull/10
=> add document build and deploy jobs

.github/workflows/CompatHelper.yml
Beside the changes in the `CompatHelper.yml` I did also:
- Generated a ssh key pair for the deployment and add it to the repository like described in the [compat helper documentation](https://juliaregistries.github.io/CompatHelper.jl/stable/#Creating-SSH-Key).
- Enable the option `Allow GitHub Actions to create and approve pull requests` option for the whole `QEDJl-project` group.
- It is not possible to enable it only for a single repository.
- Disable the option for repositories ` QEDjl-project.github.io`, `registry`, `.github`
fixes: #20
=> fix compat helper job

CHANGELOG.md
This PR add the CHANGELOG of the release of version `v0.1.0` to `dev`. 
Since this was already reviewed, it can be merged, if the checks all pass.
=> Release v0.1.0 -- Add CHANGELOG to dev

.github/workflows/BuildDeployDoc.yml
There was one more spot that was overlooked where the custom registry can be removed now.
=> Fix filename typo, remove custom registry build step

Project.toml, src/QEDprocesses.jl, src/interfaces/setup_interface.jl, src/phase_spaces.jl, test/Project.toml, test/phase_spaces.jl, test/runtests.jl
Proposal to fix issue #46
This branch is currently based on PR #39 and should be merged after it.
This is a draft for now, but I think it is a good compromise from the discussion in issue #46. The definition is type stable, allows some nice overloads for `is_fermion` and so on for the `ParticleStateful` objects, and takes care of preventing illegal objects in the constructors.
Creating particles is straightforward and disallows illegal configurations (electron with polarization or photon with spin):
```julia
in_el = ParticleStateful(rand(SFourMomentum), Electron(), AllSpin(), Incoming())
in_ph = ParticleStateful(rand(SFourMomentum), Photon(), AllPol(), Incoming())
out_el = ParticleStateful(rand(SFourMomentum), Electron(), AllSpin(), Outgoing())
out_ph = …
```
=> Add PhaseSpacePoint definition

src/QEDprocesses.jl, src/phase_spaces.jl, test/phase_spaces.jl
This adds a little convenient function `generate_phase_space` to build the new phase space points from a given process, model, phase-space definition, and lists of four-momenta for incoming and outgoing particles.
=> added generate_phase_space and respective tests

Project.toml, test/Project.toml, test/cross_sections.jl, test/interfaces/process_interface.jl
As the title says, this moves the test dependencies from `test/Project.toml` to the main `Project.toml`. To not mix these with the package dependencies, we use the `[extras]` and `[target]` blocks. 
This keeps the dependencies of the package incl. tests in one place and makes maintenance easier. Furthermore, it allows testing locally against unreleased branches of a package dependency, because the package and the tests use the same `Manifest.toml`.
=> Moved test deps to main Project.toml

.github/workflows/BuildDeployDoc.yml, .gitlab-ci.yml, Project.toml, add_QEDcore_dev.jl, src/QEDprocesses.jl, src/cross_section/diff_probability.jl, src/interfaces/process_interface.jl, src/patch_QEDbase.jl, src/phase_spaces/access.jl, src/phase_spaces/create.jl, src/phase_spaces/types.jl, src/phase_spaces/utility.jl, src/processes/one_photon_compton/perturbative/cross_section.jl, src/processes/one_photon_compton/perturbative/total_probability.jl, src/processes/one_photon_compton/process.jl, src/propagators.jl, src/restruct_patch.jl, test/interfaces/process_interface.jl, test/phase_spaces.jl, test/processes/one_photon_compton/perturbative.jl, test/processes/one_photon_compton/process.jl, test/propagators.jl, test/test_implementation/TestImplementation.jl, test/test_implementation/groundtruths.jl, test/test_implementation/test_process.jl
This opts out the `QEDbase` namespace and adds the dependency on `QEDcore`. 
This is part of the general restructuring of `QED.jl`, see https://github.com/QEDjl-project/QED.jl/issues/35 for details.
=> Refactoring QED.jl

test/cross_sections.jl, test/processes/one_photon_compton/perturbative.jl
Since `total_cross_section` moves to QEDbase, we need to qualify the calls here for now in order for integration tests to work.
Once we remove the implementation here, the `QEDbase.` calls will automatically fail and need to be removed as well.
=> Qualify total_cross_section calls

Project.toml
This bumps the version of the dev-branch to 0.1.1-DEV. 
This in only for test purposes and should not me released in the general registry. 
It only ticks up the patch version to not break compats upstream.
=> Bump dev version

.github/workflows/BuildDeployDoc.yml, .gitlab-ci.yml, add_QEDcore_dev.jl
This PR revokes the manual adding of dev dependencies in the ci.
=> Remove dev deps 

CHANGELOG.md, Project.toml
Release version 0.2.0 onto dev.
No squashing!
=> Release 0.2.0

.github/workflows/BuildDeployDoc.yml
This [QED.jl PR](https://github.com/QEDjl-project/QED.jl/pull/44) required before we can merge this PR.
=> CI: set QED dependencies for doc build to dev branch version, if target branch is not main

src/processes/one_photon_compton/perturbative/cross_section.jl, src/processes/one_photon_compton/process.jl
See https://github.com/QEDjl-project/QEDbase.jl/pull/112
=> Fix for multiplicity change in QEDbase

.github/workflows/formatter.yaml, src/QEDprocesses.jl, src/models/perturbative_qed.jl, src/processes/generic_process/perturbative/cross_section.jl, src/processes/generic_process/process.jl, src/processes/generic_process/utility.jl, src/processes/one_photon_compton/perturbative/cross_section.jl, src/processes/one_photon_compton/perturbative/total_probability.jl, test/processes/generic_process/groundtruths.jl, test/processes/generic_process/process.jl, test/processes/run_process_test.jl
Adds a generic QED process, implementing the basic `AbstractProcessDefinition` interface and allowing any combination of particles and spins/pols for them.
The constructor validates that the given spins and polarizations fit to the particles (fermion -> spin, boson -> polarization).
The actual computational functions are as of yet unimplemented and will later be added using the QEDfeynman_diagrams project, once that is public.
Therefore, for now the main use of this type is for testing purposes of other functions.
=> GenericQEDProcess

.JuliaFormatter.toml, .github/workflows/BuildDeployDoc.yml, .gitlab-ci.yml, Project.toml
Update CI scripts to the new version, same as QEDbase and QEDcore already have.
Also update compat section here as well so the CI actually works.
=> Fix CI scripts, update compats

Project.toml, README.md, src/QEDprocesses.jl, src/models/perturbative_qed.jl, src/patch_QEDbase.jl, src/processes/generic_process/process.jl, src/processes/one_photon_compton/perturbative/cross_section.jl, src/processes/one_photon_compton/perturbative/kinematics.jl, src/processes/one_photon_compton/perturbative/total_probability.jl, src/utils.jl, test/processes/one_photon_compton/perturbative/cross_section.jl, test/processes/one_photon_compton/perturbative/groundtruths.jl, test/processes/one_photon_compton/perturbative/kinematics.jl, test/processes/run_process_test.jl
* Include the proper construction of PSPs via phase space layouts. 
* implement out phase space layout for Compton scattering in spherical coordiantes
=> updated psp usage
